### ISSUE TITLE
这个问题怎么解决啊

### ISSUE THREAD

**Issue by user-deng** [2339723434/Point-Cloud-Semantic-Segmentation#1]
![1](https://github.com/2339723434/Point-Cloud-Semantic-Segmentation/assets/139295830/9b98981b-6a65-4d1b-a4f3-0aab5b8610e5)

**Comment by 2339723434** [comment]
看起来是torch-scatter的安装问题，你可以在这个网页`https://data.pyg.org/whl/`中找到自己安装的torch及cuda版本所对应的网页，例如`https://data.pyg.org/whl/torch-1.8.0%2Bcu111.html`对应`torch1.8.0`，`cuda11.1`。然后再通过`pip install torch-scatter -f https://data.pyg.org/whl/torch-1.8.0%2Bcu111.html`安装。

**Comment by user-deng** [comment]
感谢您耐心的讲解
