### ISSUE TITLE
笑死我了，你这改进的还没有人家没改的高（RepSurf）

### ISSUE THREAD

**Issue by user-deng** [2339723434/Point-Cloud-Semantic-Segmentation#3]

**Comment by 2339723434** [comment]
这边建议您用nni完成调参，并在相同的环境下做完对比试验并完成测试再来嘲讽呢。

**Comment by user-deng** [comment]
很抱歉，刚才言语有些冲动，望原谅。
我直接训练的得到的mIou 65.85   调参的话，有什么好的建议吗？

**Comment by 2339723434** [comment]
可以学习一下微软开源的调参工具nni进行调参，除了模型学习参数外，一些网络内部参数如k近邻的值也可以进行消融实验调优

**Comment by 2339723434** [comment]
另外，数据增强方式也有很大的改进空间，可以参考PointNExt进行数据增强实验，能大程度提升模型表现。此外，单独进行test的表现通常会比训练时的测试表现效果更好。

**Comment by 2339723434** [comment]
另外，数据增强方式也有很大的改进空间，可以参考PointNExt进行数据增强实验，能大程度提速模型表现

**Comment by user-deng** [comment]
谢谢您的建议
